// @generated by `cargo xtask codegen` from openapi/v1.json. Do not edit by hand.
//
// Types, query parameters and operations of the HodeiShield `/v1` API.

#![allow(
    clippy::doc_markdown,
    clippy::too_many_lines,
    clippy::struct_excessive_bools
)]

use serde::{Deserialize, Serialize};

/// `info.version` of the OpenAPI document this client was generated from.
pub const OPENAPI_VERSION: &str = "2026-09-20";

/// The server the OpenAPI document declares.
pub const DEFAULT_SERVER: &str = "https://api.hodeishield.com";

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ErrorBody {
    /// Closed vocabulary; new members may be added (see Versioning).
    ///
    /// Documented values: `invalid_request`, `unauthorized`, `forbidden`, `not_found`, `method_not_allowed`, `rate_limited`, `internal_error`, `service_unavailable`. Treat any other value as valid: the vocabulary may grow.
    pub code: String,
    /// For a human reading a log. Not stable; do not parse it.
    pub message: String,
    /// Also the `X-Request-Id` response header.
    pub request_id: String,
    /// Diagnostic. Not part of the frozen contract.
    #[serde(default)]
    pub details: Option<serde_json::Map<String, serde_json::Value>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ErrorEnvelope {
    pub error: ErrorBody,
}

/// A third party in the tenant inventory.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Vendor {
    /// Stable identifier of the vendor in this tenant.
    pub id: String,
    /// Display name.
    pub name: String,
    /// Registered legal name, when it differs.
    #[serde(default)]
    pub legal_name: Option<String>,
    /// Primary domain, lowercase, no scheme.
    #[serde(default)]
    pub domain: Option<String>,
    /// Free-text category assigned by the tenant.
    #[serde(default)]
    pub category: Option<String>,
    /// Kind of third party (provider, product, …).
    #[serde(default)]
    pub vendor_type: Option<String>,
    /// Level of access the vendor has to the tenant systems.
    #[serde(default)]
    pub access_level: Option<String>,
    /// low | medium | high | critical, as set by the tenant.
    #[serde(default)]
    pub business_criticality: Option<String>,
    /// public | internal | confidential | restricted.
    #[serde(default)]
    pub data_sensitivity: Option<String>,
    /// Estimated economic impact of an outage, in the tenant currency.
    #[serde(default)]
    pub economic_impact: Option<f64>,
    /// Whether the vendor is operationally enabled.
    pub active: bool,
    /// Continuous-monitoring state.
    #[serde(default)]
    pub monitoring_status: Option<String>,
    /// RFC 3339, UTC. Null if never scanned.
    #[serde(default)]
    pub last_scan_at: Option<String>,
    /// Legal Entity Identifier (ISO 17442), for DORA RoI.
    #[serde(default)]
    pub lei: Option<String>,
    /// Head-office country, ISO 3166-1 alpha-2.
    #[serde(default)]
    pub hq_country: Option<String>,
    /// RFC 3339, UTC.
    pub created_at: String,
    /// RFC 3339, UTC.
    pub updated_at: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Pagination {
    /// The page that was served.
    pub page: i64,
    /// Items per page in effect.
    pub per_page: i64,
    /// Total items matching the filters, across all pages.
    pub total: i64,
    /// Number of pages at this `per_page`.
    pub total_pages: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ListVendorsResponse {
    pub data: Vec<Vendor>,
    pub pagination: Pagination,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GetVendorResponse {
    /// A third party in the tenant inventory.
    pub data: Vendor,
}

/// A supply-chain alert raised against one vendor.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Alert {
    pub id: String,
    /// The vendor this alert is about (`/v1/vendors/{id}`).
    pub vendor_id: String,
    /// Alert family, e.g. `breach`, `cve`, `rating_drop`.
    pub r#type: String,
    /// critical | high | medium | low, when classified.
    #[serde(default)]
    pub severity: Option<String>,
    pub title: String,
    #[serde(default)]
    pub description: Option<String>,
    /// Where the finding came from, when public.
    #[serde(default)]
    pub source_url: Option<String>,
    #[serde(default)]
    pub economic_impact: Option<f64>,
    /// Derived: resolved if closed, acknowledged if taken, otherwise open.
    ///
    /// Documented values: `open`, `acknowledged`, `resolved`. Treat any other value as valid: the vocabulary may grow.
    pub status: String,
    /// RFC 3339, UTC.
    #[serde(default)]
    pub acknowledged_at: Option<String>,
    /// RFC 3339, UTC.
    #[serde(default)]
    pub resolved_at: Option<String>,
    /// Why it was closed, when it was.
    #[serde(default)]
    pub resolution_reason: Option<String>,
    /// RFC 3339, UTC.
    pub created_at: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ListAlertsResponse {
    pub data: Vec<Alert>,
    pub pagination: Pagination,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GetAlertResponse {
    /// A supply-chain alert raised against one vendor.
    pub data: Alert,
}

/// An entry of the tenant risk register.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Risk {
    pub id: String,
    pub title: String,
    #[serde(default)]
    pub description: Option<String>,
    /// Risk domain, as configured by the tenant.
    pub domain: String,
    /// identified | assessed | treated | accepted | closed | …
    pub status: String,
    /// mitigate | accept | transfer | avoid.
    #[serde(default)]
    pub treatment: Option<String>,
    #[serde(default)]
    pub treatment_notes: Option<String>,
    #[serde(default)]
    pub threat_source: Option<String>,
    #[serde(default)]
    pub vulnerability: Option<String>,
    pub likelihood_inherent: i64,
    pub impact_inherent: i64,
    pub inherent_score: i64,
    #[serde(default)]
    pub likelihood_residual: Option<i64>,
    #[serde(default)]
    pub impact_residual: Option<i64>,
    #[serde(default)]
    pub residual_score: Option<i64>,
    /// manual | imported | derived.
    pub source: String,
    /// User of this tenant who owns the risk.
    #[serde(default)]
    pub owner_user_id: Option<String>,
    /// The vendor this risk is about, when any.
    #[serde(default)]
    pub vendor_id: Option<String>,
    /// Framework control codes linked to the risk.
    pub control_codes: Vec<String>,
    /// Calendar date, `YYYY-MM-DD`.
    #[serde(default)]
    pub review_date: Option<String>,
    /// RFC 3339, UTC.
    pub created_at: String,
    /// RFC 3339, UTC.
    pub updated_at: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ListRisksResponse {
    pub data: Vec<Risk>,
    pub pagination: Pagination,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GetRiskResponse {
    /// An entry of the tenant risk register.
    pub data: Risk,
}

/// The tenant status of one framework control.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ComplianceControl {
    /// Framework slug the control belongs to.
    pub framework: String,
    /// Control identifier inside the framework.
    pub control_code: String,
    /// missing | partial | covered, as evaluated by the platform.
    pub status: String,
    /// Evidence items currently linked to the control.
    pub evidence_count: i64,
    /// RFC 3339, UTC.
    #[serde(default)]
    pub last_evaluated_at: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ListComplianceControlsResponse {
    pub data: Vec<ComplianceControl>,
    pub pagination: Pagination,
}

/// Posture summary for one framework.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FrameworkPosture {
    pub framework: String,
    /// Controls the platform has evaluated.
    pub controls_total: i64,
    /// Control count per status. Keys are whatever statuses exist; may grow.
    pub by_status: std::collections::BTreeMap<String, i64>,
    /// Sum of the evidence linked across the evaluated controls.
    pub evidence_total: i64,
    /// Most recent control evaluation, RFC 3339 UTC. Null if never evaluated.
    #[serde(default)]
    pub last_evaluated_at: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GetFrameworkPostureResponse {
    /// Posture summary for one framework.
    pub data: FrameworkPosture,
}

/// One item of security evidence.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Evidence {
    pub id: String,
    /// What kind of evidence this is.
    pub evidence_type: String,
    /// Which subsystem produced it.
    pub source_type: String,
    /// Its identifier inside that subsystem.
    pub source_id: String,
    pub title: String,
    #[serde(default)]
    pub description: Option<String>,
    /// The vendor it is about, when any.
    #[serde(default)]
    pub vendor_id: Option<String>,
    /// The asset it is about, when any.
    #[serde(default)]
    pub asset_id: Option<String>,
    /// False when a person uploaded it.
    pub auto_generated: bool,
    /// Calendar date, `YYYY-MM-DD`. Null = no expiry.
    #[serde(default)]
    pub valid_until: Option<String>,
    /// RFC 3339, UTC.
    pub created_at: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ListEvidenceResponse {
    pub data: Vec<Evidence>,
    pub pagination: Pagination,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GetEvidenceResponse {
    /// One item of security evidence.
    pub data: Evidence,
}

/// An endpoint agent enrolled in this tenant.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Endpoint {
    pub id: String,
    /// The agent name, unique among the active ones of the tenant.
    pub producer: String,
    /// What kind of producer it is.
    pub producer_kind: String,
    /// active | revoked.
    pub status: String,
    /// Algorithm this enrollment signs with.
    pub signature_alg: String,
    #[serde(default)]
    pub agent_version: Option<String>,
    /// Last hostname the agent reported.
    #[serde(default)]
    pub hostname: Option<String>,
    /// RFC 3339, UTC.
    pub enrolled_at: String,
    /// RFC 3339, UTC. Null until the first envelope.
    #[serde(default)]
    pub last_seen_at: Option<String>,
    /// RFC 3339, UTC.
    #[serde(default)]
    pub revoked_at: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ListEndpointsResponse {
    pub data: Vec<Endpoint>,
    pub pagination: Pagination,
}

/// Accepted values of a query parameter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum VendorSort {
    /// `created_at`
    CreatedAt,
    /// `updated_at`
    UpdatedAt,
    /// `name`
    Name,
}

impl VendorSort {
    /// Every accepted value, as sent on the wire.
    pub const VALUES: &'static [&'static str] = &["created_at", "updated_at", "name"];

    /// The value as sent on the wire.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::CreatedAt => "created_at",
            Self::UpdatedAt => "updated_at",
            Self::Name => "name",
        }
    }
}

impl std::fmt::Display for VendorSort {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::str::FromStr for VendorSort {
    type Err = crate::ParseEnumError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "created_at" => Ok(Self::CreatedAt),
            "updated_at" => Ok(Self::UpdatedAt),
            "name" => Ok(Self::Name),
            _ => Err(crate::ParseEnumError::new(value, Self::VALUES)),
        }
    }
}

/// Accepted values of a query parameter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Order {
    /// `asc`
    Asc,
    /// `desc`
    Desc,
}

impl Order {
    /// Every accepted value, as sent on the wire.
    pub const VALUES: &'static [&'static str] = &["asc", "desc"];

    /// The value as sent on the wire.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Asc => "asc",
            Self::Desc => "desc",
        }
    }
}

impl std::fmt::Display for Order {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::str::FromStr for Order {
    type Err = crate::ParseEnumError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "asc" => Ok(Self::Asc),
            "desc" => Ok(Self::Desc),
            _ => Err(crate::ParseEnumError::new(value, Self::VALUES)),
        }
    }
}

/// Accepted values of a query parameter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BusinessCriticality {
    /// `low`
    Low,
    /// `medium`
    Medium,
    /// `high`
    High,
    /// `critical`
    Critical,
}

impl BusinessCriticality {
    /// Every accepted value, as sent on the wire.
    pub const VALUES: &'static [&'static str] = &["low", "medium", "high", "critical"];

    /// The value as sent on the wire.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Low => "low",
            Self::Medium => "medium",
            Self::High => "high",
            Self::Critical => "critical",
        }
    }
}

impl std::fmt::Display for BusinessCriticality {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::str::FromStr for BusinessCriticality {
    type Err = crate::ParseEnumError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "low" => Ok(Self::Low),
            "medium" => Ok(Self::Medium),
            "high" => Ok(Self::High),
            "critical" => Ok(Self::Critical),
            _ => Err(crate::ParseEnumError::new(value, Self::VALUES)),
        }
    }
}

/// Accepted values of a query parameter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AlertSort {
    /// `created_at`
    CreatedAt,
}

impl AlertSort {
    /// Every accepted value, as sent on the wire.
    pub const VALUES: &'static [&'static str] = &["created_at"];

    /// The value as sent on the wire.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::CreatedAt => "created_at",
        }
    }
}

impl std::fmt::Display for AlertSort {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::str::FromStr for AlertSort {
    type Err = crate::ParseEnumError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "created_at" => Ok(Self::CreatedAt),
            _ => Err(crate::ParseEnumError::new(value, Self::VALUES)),
        }
    }
}

/// Accepted values of a query parameter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AlertStatus {
    /// `open`
    Open,
    /// `acknowledged`
    Acknowledged,
    /// `resolved`
    Resolved,
}

impl AlertStatus {
    /// Every accepted value, as sent on the wire.
    pub const VALUES: &'static [&'static str] = &["open", "acknowledged", "resolved"];

    /// The value as sent on the wire.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Open => "open",
            Self::Acknowledged => "acknowledged",
            Self::Resolved => "resolved",
        }
    }
}

impl std::fmt::Display for AlertStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::str::FromStr for AlertStatus {
    type Err = crate::ParseEnumError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "open" => Ok(Self::Open),
            "acknowledged" => Ok(Self::Acknowledged),
            "resolved" => Ok(Self::Resolved),
            _ => Err(crate::ParseEnumError::new(value, Self::VALUES)),
        }
    }
}

/// Accepted values of a query parameter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RiskSort {
    /// `created_at`
    CreatedAt,
    /// `updated_at`
    UpdatedAt,
    /// `inherent_score`
    InherentScore,
    /// `residual_score`
    ResidualScore,
}

impl RiskSort {
    /// Every accepted value, as sent on the wire.
    pub const VALUES: &'static [&'static str] = &[
        "created_at",
        "updated_at",
        "inherent_score",
        "residual_score",
    ];

    /// The value as sent on the wire.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::CreatedAt => "created_at",
            Self::UpdatedAt => "updated_at",
            Self::InherentScore => "inherent_score",
            Self::ResidualScore => "residual_score",
        }
    }
}

impl std::fmt::Display for RiskSort {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::str::FromStr for RiskSort {
    type Err = crate::ParseEnumError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "created_at" => Ok(Self::CreatedAt),
            "updated_at" => Ok(Self::UpdatedAt),
            "inherent_score" => Ok(Self::InherentScore),
            "residual_score" => Ok(Self::ResidualScore),
            _ => Err(crate::ParseEnumError::new(value, Self::VALUES)),
        }
    }
}

/// Accepted values of a query parameter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ComplianceControlSort {
    /// `control_code`
    ControlCode,
    /// `last_evaluated_at`
    LastEvaluatedAt,
}

impl ComplianceControlSort {
    /// Every accepted value, as sent on the wire.
    pub const VALUES: &'static [&'static str] = &["control_code", "last_evaluated_at"];

    /// The value as sent on the wire.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::ControlCode => "control_code",
            Self::LastEvaluatedAt => "last_evaluated_at",
        }
    }
}

impl std::fmt::Display for ComplianceControlSort {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::str::FromStr for ComplianceControlSort {
    type Err = crate::ParseEnumError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "control_code" => Ok(Self::ControlCode),
            "last_evaluated_at" => Ok(Self::LastEvaluatedAt),
            _ => Err(crate::ParseEnumError::new(value, Self::VALUES)),
        }
    }
}

/// Accepted values of a query parameter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EvidenceSort {
    /// `created_at`
    CreatedAt,
    /// `valid_until`
    ValidUntil,
}

impl EvidenceSort {
    /// Every accepted value, as sent on the wire.
    pub const VALUES: &'static [&'static str] = &["created_at", "valid_until"];

    /// The value as sent on the wire.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::CreatedAt => "created_at",
            Self::ValidUntil => "valid_until",
        }
    }
}

impl std::fmt::Display for EvidenceSort {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::str::FromStr for EvidenceSort {
    type Err = crate::ParseEnumError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "created_at" => Ok(Self::CreatedAt),
            "valid_until" => Ok(Self::ValidUntil),
            _ => Err(crate::ParseEnumError::new(value, Self::VALUES)),
        }
    }
}

/// Accepted values of a query parameter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EndpointSort {
    /// `enrolled_at`
    EnrolledAt,
    /// `last_seen_at`
    LastSeenAt,
    /// `producer`
    Producer,
}

impl EndpointSort {
    /// Every accepted value, as sent on the wire.
    pub const VALUES: &'static [&'static str] = &["enrolled_at", "last_seen_at", "producer"];

    /// The value as sent on the wire.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::EnrolledAt => "enrolled_at",
            Self::LastSeenAt => "last_seen_at",
            Self::Producer => "producer",
        }
    }
}

impl std::fmt::Display for EndpointSort {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::str::FromStr for EndpointSort {
    type Err = crate::ParseEnumError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "enrolled_at" => Ok(Self::EnrolledAt),
            "last_seen_at" => Ok(Self::LastSeenAt),
            "producer" => Ok(Self::Producer),
            _ => Err(crate::ParseEnumError::new(value, Self::VALUES)),
        }
    }
}

/// Accepted values of a query parameter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EndpointStatus {
    /// `active`
    Active,
    /// `revoked`
    Revoked,
}

impl EndpointStatus {
    /// Every accepted value, as sent on the wire.
    pub const VALUES: &'static [&'static str] = &["active", "revoked"];

    /// The value as sent on the wire.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Revoked => "revoked",
        }
    }
}

impl std::fmt::Display for EndpointStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::str::FromStr for EndpointStatus {
    type Err = crate::ParseEnumError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "active" => Ok(Self::Active),
            "revoked" => Ok(Self::Revoked),
            _ => Err(crate::ParseEnumError::new(value, Self::VALUES)),
        }
    }
}

/// Query parameters of `listVendors`.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct ListVendorsParams {
    /// 1-based page number. Defaults to 1.
    pub page: Option<i64>,
    /// Items per page, 1..200. Defaults to 50.
    pub per_page: Option<i64>,
    /// Field to order by. One of: created_at, updated_at, name.
    pub sort: Option<VendorSort>,
    /// Sort direction. Defaults to desc.
    pub order: Option<Order>,
    /// Case-insensitive substring of the name or the domain.
    pub q: Option<String>,
    /// Exact category match.
    pub category: Option<String>,
    /// Filter by the operational flag.
    pub active: Option<String>,
    /// Exact criticality match.
    pub business_criticality: Option<BusinessCriticality>,
}

impl ListVendorsParams {
    /// The query string, in document order, without the parameters that are unset.
    #[must_use]
    pub fn query_pairs(&self) -> Vec<(&'static str, String)> {
        let mut pairs = Vec::new();
        if let Some(value) = &self.page {
            pairs.push(("page", value.to_string()));
        }
        if let Some(value) = &self.per_page {
            pairs.push(("per_page", value.to_string()));
        }
        if let Some(value) = &self.sort {
            pairs.push(("sort", value.as_str().to_owned()));
        }
        if let Some(value) = &self.order {
            pairs.push(("order", value.as_str().to_owned()));
        }
        if let Some(value) = &self.q {
            pairs.push(("q", value.clone()));
        }
        if let Some(value) = &self.category {
            pairs.push(("category", value.clone()));
        }
        if let Some(value) = &self.active {
            pairs.push(("active", value.clone()));
        }
        if let Some(value) = &self.business_criticality {
            pairs.push(("business_criticality", value.as_str().to_owned()));
        }
        pairs
    }
}

/// Query parameters of `listAlerts`.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct ListAlertsParams {
    /// 1-based page number. Defaults to 1.
    pub page: Option<i64>,
    /// Items per page, 1..200. Defaults to 50.
    pub per_page: Option<i64>,
    /// Field to order by. One of: created_at.
    pub sort: Option<AlertSort>,
    /// Sort direction. Defaults to desc.
    pub order: Option<Order>,
    /// Filter by the derived status.
    pub status: Option<AlertStatus>,
    /// Exact severity match.
    pub severity: Option<String>,
    /// Only alerts about this vendor.
    pub vendor_id: Option<String>,
    /// Only alerts created at or after this RFC 3339 instant.
    pub since: Option<String>,
}

impl ListAlertsParams {
    /// The query string, in document order, without the parameters that are unset.
    #[must_use]
    pub fn query_pairs(&self) -> Vec<(&'static str, String)> {
        let mut pairs = Vec::new();
        if let Some(value) = &self.page {
            pairs.push(("page", value.to_string()));
        }
        if let Some(value) = &self.per_page {
            pairs.push(("per_page", value.to_string()));
        }
        if let Some(value) = &self.sort {
            pairs.push(("sort", value.as_str().to_owned()));
        }
        if let Some(value) = &self.order {
            pairs.push(("order", value.as_str().to_owned()));
        }
        if let Some(value) = &self.status {
            pairs.push(("status", value.as_str().to_owned()));
        }
        if let Some(value) = &self.severity {
            pairs.push(("severity", value.clone()));
        }
        if let Some(value) = &self.vendor_id {
            pairs.push(("vendor_id", value.clone()));
        }
        if let Some(value) = &self.since {
            pairs.push(("since", value.clone()));
        }
        pairs
    }
}

/// Query parameters of `listRisks`.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct ListRisksParams {
    /// 1-based page number. Defaults to 1.
    pub page: Option<i64>,
    /// Items per page, 1..200. Defaults to 50.
    pub per_page: Option<i64>,
    /// Field to order by. One of: created_at, updated_at, inherent_score, residual_score.
    pub sort: Option<RiskSort>,
    /// Sort direction. Defaults to desc.
    pub order: Option<Order>,
    /// Exact status match.
    pub status: Option<String>,
    /// Exact domain match.
    pub domain: Option<String>,
    /// Only risks linked to this vendor.
    pub vendor_id: Option<String>,
    /// Only risks whose inherent score is at least this.
    pub min_inherent_score: Option<i64>,
}

impl ListRisksParams {
    /// The query string, in document order, without the parameters that are unset.
    #[must_use]
    pub fn query_pairs(&self) -> Vec<(&'static str, String)> {
        let mut pairs = Vec::new();
        if let Some(value) = &self.page {
            pairs.push(("page", value.to_string()));
        }
        if let Some(value) = &self.per_page {
            pairs.push(("per_page", value.to_string()));
        }
        if let Some(value) = &self.sort {
            pairs.push(("sort", value.as_str().to_owned()));
        }
        if let Some(value) = &self.order {
            pairs.push(("order", value.as_str().to_owned()));
        }
        if let Some(value) = &self.status {
            pairs.push(("status", value.clone()));
        }
        if let Some(value) = &self.domain {
            pairs.push(("domain", value.clone()));
        }
        if let Some(value) = &self.vendor_id {
            pairs.push(("vendor_id", value.clone()));
        }
        if let Some(value) = &self.min_inherent_score {
            pairs.push(("min_inherent_score", value.to_string()));
        }
        pairs
    }
}

/// Query parameters of `listComplianceControls`.
#[derive(Debug, Clone, PartialEq)]
pub struct ListComplianceControlsParams {
    /// 1-based page number. Defaults to 1.
    pub page: Option<i64>,
    /// Items per page, 1..200. Defaults to 50.
    pub per_page: Option<i64>,
    /// Field to order by. One of: control_code, last_evaluated_at.
    pub sort: Option<ComplianceControlSort>,
    /// Sort direction. Defaults to desc.
    pub order: Option<Order>,
    /// Framework slug. One of: nis2, ens, iso27001, dora, gdpr, soc2, iso42001, nistcsf, pcidss, euaiact, hipaa, cmmc, cyberessentials, uaeia, sama, saudiecc, ndpa.
    pub framework: String,
    /// Exact status match.
    pub status: Option<String>,
}

impl ListComplianceControlsParams {
    /// Parameters with every optional one unset.
    #[must_use]
    pub fn new(framework: impl Into<String>) -> Self {
        Self {
            page: None,
            per_page: None,
            sort: None,
            order: None,
            framework: framework.into(),
            status: None,
        }
    }

    /// The query string, in document order, without the parameters that are unset.
    #[must_use]
    pub fn query_pairs(&self) -> Vec<(&'static str, String)> {
        let mut pairs = Vec::new();
        if let Some(value) = &self.page {
            pairs.push(("page", value.to_string()));
        }
        if let Some(value) = &self.per_page {
            pairs.push(("per_page", value.to_string()));
        }
        if let Some(value) = &self.sort {
            pairs.push(("sort", value.as_str().to_owned()));
        }
        if let Some(value) = &self.order {
            pairs.push(("order", value.as_str().to_owned()));
        }
        pairs.push(("framework", self.framework.clone()));
        if let Some(value) = &self.status {
            pairs.push(("status", value.clone()));
        }
        pairs
    }
}

/// Query parameters of `listEvidence`.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct ListEvidenceParams {
    /// 1-based page number. Defaults to 1.
    pub page: Option<i64>,
    /// Items per page, 1..200. Defaults to 50.
    pub per_page: Option<i64>,
    /// Field to order by. One of: created_at, valid_until.
    pub sort: Option<EvidenceSort>,
    /// Sort direction. Defaults to desc.
    pub order: Option<Order>,
    /// Exact type match.
    pub evidence_type: Option<String>,
    /// Exact producer match.
    pub source_type: Option<String>,
    /// Only evidence about this vendor.
    pub vendor_id: Option<String>,
    /// Only evidence with a `valid_until` strictly before this `YYYY-MM-DD`.
    pub expiring_before: Option<String>,
}

impl ListEvidenceParams {
    /// The query string, in document order, without the parameters that are unset.
    #[must_use]
    pub fn query_pairs(&self) -> Vec<(&'static str, String)> {
        let mut pairs = Vec::new();
        if let Some(value) = &self.page {
            pairs.push(("page", value.to_string()));
        }
        if let Some(value) = &self.per_page {
            pairs.push(("per_page", value.to_string()));
        }
        if let Some(value) = &self.sort {
            pairs.push(("sort", value.as_str().to_owned()));
        }
        if let Some(value) = &self.order {
            pairs.push(("order", value.as_str().to_owned()));
        }
        if let Some(value) = &self.evidence_type {
            pairs.push(("evidence_type", value.clone()));
        }
        if let Some(value) = &self.source_type {
            pairs.push(("source_type", value.clone()));
        }
        if let Some(value) = &self.vendor_id {
            pairs.push(("vendor_id", value.clone()));
        }
        if let Some(value) = &self.expiring_before {
            pairs.push(("expiring_before", value.clone()));
        }
        pairs
    }
}

/// Query parameters of `listEndpoints`.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct ListEndpointsParams {
    /// 1-based page number. Defaults to 1.
    pub page: Option<i64>,
    /// Items per page, 1..200. Defaults to 50.
    pub per_page: Option<i64>,
    /// Field to order by. One of: enrolled_at, last_seen_at, producer.
    pub sort: Option<EndpointSort>,
    /// Sort direction. Defaults to desc.
    pub order: Option<Order>,
    /// Exact status match.
    pub status: Option<EndpointStatus>,
    /// Agents last seen before this RFC 3339 instant, or never seen at all.
    pub silent_since: Option<String>,
}

impl ListEndpointsParams {
    /// The query string, in document order, without the parameters that are unset.
    #[must_use]
    pub fn query_pairs(&self) -> Vec<(&'static str, String)> {
        let mut pairs = Vec::new();
        if let Some(value) = &self.page {
            pairs.push(("page", value.to_string()));
        }
        if let Some(value) = &self.per_page {
            pairs.push(("per_page", value.to_string()));
        }
        if let Some(value) = &self.sort {
            pairs.push(("sort", value.as_str().to_owned()));
        }
        if let Some(value) = &self.order {
            pairs.push(("order", value.as_str().to_owned()));
        }
        if let Some(value) = &self.status {
            pairs.push(("status", value.as_str().to_owned()));
        }
        if let Some(value) = &self.silent_since {
            pairs.push(("silent_since", value.clone()));
        }
        pairs
    }
}

/// Every `/v1` operation, as the OpenAPI document describes it.
pub mod operations {
    use crate::Operation;

    /// `GET /v1/vendors`: List third parties.
    pub const LIST_VENDORS: Operation = Operation {
        id: "listVendors",
        method: "GET",
        path: "/v1/vendors",
        summary: "List third parties",
        scopes: &["supply_risk:read"],
    };

    /// `GET /v1/vendors/{id}`: Fetch one third party.
    pub const GET_VENDOR: Operation = Operation {
        id: "getVendor",
        method: "GET",
        path: "/v1/vendors/{id}",
        summary: "Fetch one third party",
        scopes: &["supply_risk:read"],
    };

    /// `GET /v1/alerts`: List supply-chain alerts.
    pub const LIST_ALERTS: Operation = Operation {
        id: "listAlerts",
        method: "GET",
        path: "/v1/alerts",
        summary: "List supply-chain alerts",
        scopes: &["supply_risk:read"],
    };

    /// `GET /v1/alerts/{id}`: Fetch one alert.
    pub const GET_ALERT: Operation = Operation {
        id: "getAlert",
        method: "GET",
        path: "/v1/alerts/{id}",
        summary: "Fetch one alert",
        scopes: &["supply_risk:read"],
    };

    /// `GET /v1/risks`: List risk-register entries.
    pub const LIST_RISKS: Operation = Operation {
        id: "listRisks",
        method: "GET",
        path: "/v1/risks",
        summary: "List risk-register entries",
        scopes: &["supply_risk:read"],
    };

    /// `GET /v1/risks/{id}`: Fetch one risk-register entry.
    pub const GET_RISK: Operation = Operation {
        id: "getRisk",
        method: "GET",
        path: "/v1/risks/{id}",
        summary: "Fetch one risk-register entry",
        scopes: &["supply_risk:read"],
    };

    /// `GET /v1/compliance/controls`: List control status for a framework.
    pub const LIST_COMPLIANCE_CONTROLS: Operation = Operation {
        id: "listComplianceControls",
        method: "GET",
        path: "/v1/compliance/controls",
        summary: "List control status for a framework",
        scopes: &["compliance.<framework>:read"],
    };

    /// `GET /v1/compliance/frameworks/{framework}`: Framework posture summary.
    pub const GET_FRAMEWORK_POSTURE: Operation = Operation {
        id: "getFrameworkPosture",
        method: "GET",
        path: "/v1/compliance/frameworks/{framework}",
        summary: "Framework posture summary",
        scopes: &["compliance.<framework>:read"],
    };

    /// `GET /v1/evidence`: List security evidence.
    pub const LIST_EVIDENCE: Operation = Operation {
        id: "listEvidence",
        method: "GET",
        path: "/v1/evidence",
        summary: "List security evidence",
        scopes: &["evidence:read"],
    };

    /// `GET /v1/evidence/{id}`: Fetch one evidence item.
    pub const GET_EVIDENCE: Operation = Operation {
        id: "getEvidence",
        method: "GET",
        path: "/v1/evidence/{id}",
        summary: "Fetch one evidence item",
        scopes: &["evidence:read"],
    };

    /// `GET /v1/endpoints`: List enrolled endpoint agents.
    pub const LIST_ENDPOINTS: Operation = Operation {
        id: "listEndpoints",
        method: "GET",
        path: "/v1/endpoints",
        summary: "List enrolled endpoint agents",
        scopes: &["endpoints:read"],
    };

    /// All operations, in document order.
    pub const ALL: &[Operation] = &[
        LIST_VENDORS,
        GET_VENDOR,
        LIST_ALERTS,
        GET_ALERT,
        LIST_RISKS,
        GET_RISK,
        LIST_COMPLIANCE_CONTROLS,
        GET_FRAMEWORK_POSTURE,
        LIST_EVIDENCE,
        GET_EVIDENCE,
        LIST_ENDPOINTS,
    ];
}

impl crate::Client {
    /// List third parties.
    ///
    /// The tenant third-party inventory, newest first by default. Soft-deleted vendors are never returned.
    ///
    /// Required scope: `supply_risk:read`. Published in `/v1` since 2026-09-20.
    ///
    /// # Errors
    ///
    /// [`crate::Error`] when the request cannot be sent, the API answers with an error, or the
    /// body does not match the document.
    pub fn list_vendors(
        &self,
        params: &ListVendorsParams,
    ) -> Result<crate::ApiResponse<ListVendorsResponse>, crate::Error> {
        self.get(
            &operations::LIST_VENDORS,
            "/v1/vendors".to_owned(),
            params.query_pairs(),
        )
    }

    /// Fetch one third party.
    ///
    /// The same object `listVendors` returns, for a single vendor.
    ///
    /// Required scope: `supply_risk:read`. Published in `/v1` since 2026-09-20.
    ///
    /// # Errors
    ///
    /// [`crate::Error`] when the request cannot be sent, the API answers with an error, or the
    /// body does not match the document.
    pub fn get_vendor(
        &self,
        id: &str,
    ) -> Result<crate::ApiResponse<GetVendorResponse>, crate::Error> {
        self.get(
            &operations::GET_VENDOR,
            format!("/v1/vendors/{}", crate::encode_path_segment(id)?),
            Vec::new(),
        )
    }

    /// List supply-chain alerts.
    ///
    /// Alerts raised against the tenant vendors. Poll incrementally with `since` plus `order=asc`.
    ///
    /// Required scope: `supply_risk:read`. Published in `/v1` since 2026-09-20.
    ///
    /// # Errors
    ///
    /// [`crate::Error`] when the request cannot be sent, the API answers with an error, or the
    /// body does not match the document.
    pub fn list_alerts(
        &self,
        params: &ListAlertsParams,
    ) -> Result<crate::ApiResponse<ListAlertsResponse>, crate::Error> {
        self.get(
            &operations::LIST_ALERTS,
            "/v1/alerts".to_owned(),
            params.query_pairs(),
        )
    }

    /// Fetch one alert.
    ///
    /// The same object `listAlerts` returns, for a single alert.
    ///
    /// Required scope: `supply_risk:read`. Published in `/v1` since 2026-09-20.
    ///
    /// # Errors
    ///
    /// [`crate::Error`] when the request cannot be sent, the API answers with an error, or the
    /// body does not match the document.
    pub fn get_alert(
        &self,
        id: &str,
    ) -> Result<crate::ApiResponse<GetAlertResponse>, crate::Error> {
        self.get(
            &operations::GET_ALERT,
            format!("/v1/alerts/{}", crate::encode_path_segment(id)?),
            Vec::new(),
        )
    }

    /// List risk-register entries.
    ///
    /// The tenant risk register, with inherent and residual figures.
    ///
    /// Required scope: `supply_risk:read`. Published in `/v1` since 2026-09-20.
    ///
    /// # Errors
    ///
    /// [`crate::Error`] when the request cannot be sent, the API answers with an error, or the
    /// body does not match the document.
    pub fn list_risks(
        &self,
        params: &ListRisksParams,
    ) -> Result<crate::ApiResponse<ListRisksResponse>, crate::Error> {
        self.get(
            &operations::LIST_RISKS,
            "/v1/risks".to_owned(),
            params.query_pairs(),
        )
    }

    /// Fetch one risk-register entry.
    ///
    /// The same object `listRisks` returns, for a single entry.
    ///
    /// Required scope: `supply_risk:read`. Published in `/v1` since 2026-09-20.
    ///
    /// # Errors
    ///
    /// [`crate::Error`] when the request cannot be sent, the API answers with an error, or the
    /// body does not match the document.
    pub fn get_risk(&self, id: &str) -> Result<crate::ApiResponse<GetRiskResponse>, crate::Error> {
        self.get(
            &operations::GET_RISK,
            format!("/v1/risks/{}", crate::encode_path_segment(id)?),
            Vec::new(),
        )
    }

    /// List control status for a framework.
    ///
    /// Per-control status of one framework. Requires the read scope OF THAT FRAMEWORK: `compliance.<framework>:read`.
    ///
    /// Required scope: `compliance.<framework>:read`. Published in `/v1` since 2026-09-20.
    ///
    /// # Errors
    ///
    /// [`crate::Error`] when the request cannot be sent, the API answers with an error, or the
    /// body does not match the document.
    pub fn list_compliance_controls(
        &self,
        params: &ListComplianceControlsParams,
    ) -> Result<crate::ApiResponse<ListComplianceControlsResponse>, crate::Error> {
        self.get(
            &operations::LIST_COMPLIANCE_CONTROLS,
            "/v1/compliance/controls".to_owned(),
            params.query_pairs(),
        )
    }

    /// Framework posture summary.
    ///
    /// Counts of evaluated controls by status for one framework, for a dashboard tile. Requires `compliance.<framework>:read`.
    ///
    /// Required scope: `compliance.<framework>:read`. Published in `/v1` since 2026-09-20.
    ///
    /// # Errors
    ///
    /// [`crate::Error`] when the request cannot be sent, the API answers with an error, or the
    /// body does not match the document.
    pub fn get_framework_posture(
        &self,
        framework: &str,
    ) -> Result<crate::ApiResponse<GetFrameworkPostureResponse>, crate::Error> {
        self.get(
            &operations::GET_FRAMEWORK_POSTURE,
            format!(
                "/v1/compliance/frameworks/{}",
                crate::encode_path_segment(framework)?
            ),
            Vec::new(),
        )
    }

    /// List security evidence.
    ///
    /// Evidence held for the tenant. Use `expiring_before` plus `sort=valid_until&order=asc` for a renewal queue.
    ///
    /// Required scope: `evidence:read`. Published in `/v1` since 2026-09-20.
    ///
    /// # Errors
    ///
    /// [`crate::Error`] when the request cannot be sent, the API answers with an error, or the
    /// body does not match the document.
    pub fn list_evidence(
        &self,
        params: &ListEvidenceParams,
    ) -> Result<crate::ApiResponse<ListEvidenceResponse>, crate::Error> {
        self.get(
            &operations::LIST_EVIDENCE,
            "/v1/evidence".to_owned(),
            params.query_pairs(),
        )
    }

    /// Fetch one evidence item.
    ///
    /// The same object `listEvidence` returns, for a single item.
    ///
    /// Required scope: `evidence:read`. Published in `/v1` since 2026-09-20.
    ///
    /// # Errors
    ///
    /// [`crate::Error`] when the request cannot be sent, the API answers with an error, or the
    /// body does not match the document.
    pub fn get_evidence(
        &self,
        id: &str,
    ) -> Result<crate::ApiResponse<GetEvidenceResponse>, crate::Error> {
        self.get(
            &operations::GET_EVIDENCE,
            format!("/v1/evidence/{}", crate::encode_path_segment(id)?),
            Vec::new(),
        )
    }

    /// List enrolled endpoint agents.
    ///
    /// The endpoint agents enrolled in this tenant. `silent_since` selects the ones that have gone quiet, including those that never reported.
    ///
    /// Required scope: `endpoints:read`. Published in `/v1` since 2026-09-20.
    ///
    /// # Errors
    ///
    /// [`crate::Error`] when the request cannot be sent, the API answers with an error, or the
    /// body does not match the document.
    pub fn list_endpoints(
        &self,
        params: &ListEndpointsParams,
    ) -> Result<crate::ApiResponse<ListEndpointsResponse>, crate::Error> {
        self.get(
            &operations::LIST_ENDPOINTS,
            "/v1/endpoints".to_owned(),
            params.query_pairs(),
        )
    }
}
